on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      board: xiao_ble
      shield: |
        roBa_L
        roBa_R
        settings_reset
      snippet: studio-rpc-usb-uart


#on: [push, pull_request, workflow_dispatch]
#
#jobs:
#  build:
#    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
